:toc: left
:toclevels: 5
:sectnums:

= 在庫管理アプリケーション開発演習

== 要件
=== 在庫管理の業務内容
在庫管理は仕入れと販売の間に位置する業務である。

具体的には以下の種類の業務が存在する。

==== 仕入入荷
仕入先に発注した商品が倉庫などに納品されることを「仕入入荷」という。

この時、発注内容と納入されてきた商品の種類、数量、品質などに問題がないかをチェック（検品）する。

検品の結果、問題がなければ納入された商品を倉庫の所定場所に保管する（入庫）。
[plantuml]
----
|仕入担当|
start
:商品を注文する;
|仕入先|
:注文を受ける;
:商品を出荷する;
|倉庫担当|
:商品を検品する;
:商品を入庫する;
stop
----

==== 販売出荷
顧客からの受注内容に基づいて、倉庫担当が商品を出荷する作業である。

この出荷作業を行うために、必要な商品を集める作業を「ピッキング」と言う。

販売出荷の場合は、出荷用に集めた商品を納品用に梱包し、納品書などの納入書類をつけて顧客宛の配送に出す。
[plantuml]
----
|顧客|
start
:商品を注文する;
|販売担当|
:注文を受ける;
:出荷を支持する;
|倉庫担当|
:商品をピッキングする;
:商品を梱包する;
:商品を発送する;
|顧客|
:商品を受領する;
----

==== 移送入庫／出荷
商品を倉庫から別の倉庫へ移すことを「移送」と呼ぶ。

この移送のために、移送元の倉庫から出庫して、移送先の倉庫に入庫する作業をそれぞれ「移送出庫」「移送入庫」と呼ぶ。

これらの作業自体は、仕入入荷と販売出荷と大きく違わないが、添付する書類の種類が違ったり、梱包や検品の作業内容が違うなどの特徴がある。

==== 返品入庫／出庫
顧客に出荷した商品が返品されてきた場合の入庫作業を「返品入庫」と呼ぶ。

顧客からの返品には、例えば、不良品で返品されてたり、顧客都合で返品されたりなど、様々な原因がある。

返品入庫では、商品の検品を行うだけでなく、こうした返品理由を確認してから、そのまま再度入庫するのか、不良品として廃棄するなどの対応をとるかを判断する。

また、仕入先に商品を返品する作業のことを「返品出荷」と呼ぶ。

==== 棚卸
商品在庫の数量や品質をチェックする作業を「棚卸」と呼ぶ。

==== そのほかの作業
そのほかにも、在庫管理にはさまざまな作業がある。

=== 在庫管理業務のユースケース
これらの業務のうち、商品の入庫及び商品の出庫・棚卸業務をシステム化の範囲とする。

[plantuml]
----
left to right direction
skinparam packageStyle rectangle
actor 倉庫担当
rectangle 在庫管理業務 {
  倉庫担当 -- (商品を入庫する)
  倉庫担当 -- (商品を出庫する)
  倉庫担当 -- (商品在庫を棚卸する)
  (商品を入庫する) -- (仕入商品を入荷する) :<<extend>>
  (商品を入庫する) -- (移送品を入庫する) :<<extend>>
  (商品を入庫する) -- (返品を入庫する) :<<extend>>
  (商品を出庫する) -- (販売商品を出庫する) :<<extend>>
  (商品を出庫する) -- (移送品を出庫する) :<<extend>>
  (商品を出庫する) -- (返品を出庫する) :<<extend>>
}
----

== 仕様

|===
|No |ユースケース |概要

|UC-01
|商品を入庫する
|倉庫担当は倉庫宛に送付された商品が、種類／数量が正しいか、品質に問題がないかをチェックする。問題がなければ商品を所定の場所で保管する。

|UC-02
|仕入れ商品を入庫する
|倉庫担当は、倉庫宛に送付されてきた商品が、仕入先に対する発注内容と、種類／数量が正しいか、品質に問題がないかをチェックする。問題がなければ商品を所定の場所で保管する。

|UC-03
|移送品を入庫する
|倉庫担当は、ほかの倉庫から送付されてきた商品が、発注内容と、種類／数量が正しいか、品質に問題がないかをチェックする。問題がなければ商品を所定の場所で保管する

|UC-04
|返品を入庫する
|倉庫担当は、顧客から返品されてきた商品が、出荷内容と、種類／数量が正しいか、品質に問題がないかをチェックする。問題がなければ商品を所定の場所で保管する。

|UC-05
|商品を出庫する
|倉庫担当は、出荷指示において指定された種類／数量の商品をピッキングし、梱包して出庫する。

|UC-06
|販売商品を出荷する
|倉庫担当は、出荷指示において指定された種類／数量の商品をピッキングし、梱包。納品書などの書類を添付して出荷する。

|UC-07
|移送品を出庫する
|倉庫担当は、移送指示において指定された種類／数量の商品をピッキングし、梱包。送り状などの書類を添付して出荷する。

|UC-08
|返品を出荷する
|倉庫担当は、返品指示において指定された商品をピッキングし、梱包。送り状などの書類を添付して仕入先に出荷する。

|UC-09
|商品在庫を棚卸する
|倉庫担当は、商品在庫の実数を調査し、システムに登録する。
|===

=== UC-02:仕入れ商品を入荷する
* CSVファイルを読み込み集計した結果をCSVファイルに出力する
* 読み込みCSVファイルは商品名ごとに受入数を集計する
* 読み込みCSVファイル仕様は以下とする

ファイルフォーマット
```
商品名,受入数
<String>,<Number>
```
ファイル名

`YYYYMMDD_INPUT.csv`

`YYYYMMDD` には作成年月日が入る

サンプルイメージはlink:./20180701_INPUT.csv[20180701_INPUT.csv]を参照
[source, csv]
----
include::20180701_INPUT.csv[]
----

* 出力CSVファイル仕様は以下とする

ファイルフォーマット
```
商品名,受入数
<String>,<Number>
```
ファイル名

`YYYYMMDD_OUTPUT.csv`

`YYYYMMDD` には作成年月日が入る

サンプルイメージはlink:./20180701_OUTPUT.csv[20180701_OUTPUT.csv]を参照
[source, csv]
----
include::20180701_OUTPUT.csv[]
----

=== UC-03:移送品を入庫する

=== UC-04:返品を入庫する

=== UC-06:販売商品を出荷する

=== UC-07:移送品を出庫する

=== UC-08:返品を出庫する

=== UC-09:商品在庫を棚卸する

== 設計
=== TODOリスト

=== ユースケース図

=== クラス図

=== シーケンス図

== 実装

== 参照
* Asciidoctor[http://asciidoctor.org/]
* PlantUML[http://www.plantuml.com]
